function fbraux = fbrAnzatz31(x1,y1,x2,y2,dtt,c,muu)
%FBRANZATZ31
%    FBRAUX = FBRANZATZ31(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    07-Nov-2019 04:26:01

t2 = -x2;
t3 = t2+x1;
fbraux = c.*dtt.*t3.*mp('1.0')./(c.*((y1-y2).^2+t3.^2)+mp('1.0')).^(mp('3.0')./mp('2.0'));
