function fbraux = fbrGram36(x1,y1,x2,y2,dtt,c,muu)
%FBRGRAM36
%    FBRAUX = FBRGRAM36(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    07-Nov-2019 04:20:44

fbraux = mp('0.0');
