function fbraux = fbrGram31(x1,y1,x2,y2,dtt,c,muu)
%FBRGRAM31
%    FBRAUX = FBRGRAM31(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    07-Nov-2019 03:54:50

t2 = y1.*mp('2.0');
t3 = y1.*mp('3.0');
t4 = y2.*mp('2.0');
t5 = y2.*mp('3.0');
t6 = -x2;
t7 = -y2;
t8 = t6+x1;
t9 = t7+y1;
t10 = t8.^2;
t11 = t9.^2;
t12 = t10+t11;
t13 = c.*t12;
t14 = t13+mp('1.0');
fbraux = c.*mp('1.0')./t14.^(mp('9.0')./mp('2.0')).*(t14.^3-c.*t11.*t14.^2.*mp('3.0')+c.*dtt.*muu.*(c.*(t3-t5+t8).*(t3-t5-x1+x2).*-mp('3.0')+c.*t13.*(t2-t4+t8).*(t2-t4-x1+x2)+mp('4.0')).*mp('3.0'));
