function fbraux = fbrGram22(x1,y1,x2,y2,dtt,c,muu)
%FBRGRAM22
%    FBRAUX = FBRGRAM22(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    07-Nov-2019 04:20:03

t2 = c.^2;
t3 = muu.^2;
t4 = x1.*mp('2.0');
t5 = x1.*mp('3.0');
t6 = x2.*mp('2.0');
t7 = x2.*mp('3.0');
t8 = -x2;
t11 = -y1;
t12 = -y2;
t9 = -t6;
t10 = -t7;
t13 = t8+x1;
t14 = t12+y1;
t15 = t13.^2;
t16 = t14.^2;
t17 = t15.*mp('5.0');
t18 = t16.*mp('2.0');
t19 = -t16;
t20 = t15+t16;
t21 = c.*t20;
t22 = t20.^2;
t23 = t21+mp('1.0');
fbraux = c.*mp('1.0')./t23.^(mp('1.3e+1')./mp('2.0')).*(dtt.^2.*(c.*(t17+t18-t2.*(t3.*(t15.*mp('2.8e+1')+t20).*mp('9.0e+1')+t22.*(t16.*mp('4.0')-t17)).*mp('2.0')+c.*(t3.*mp('1.8e+2')+t15.*t16.*mp('4.0')+t15.*t17+t16.*t19).*mp('2.0')-c.^2.*t21.*(t22.*(t16.*mp('7.0')-t17)-t3.*(t15.*mp('1.01e+2')-t16.*mp('1.1e+1')).*mp('4.5e+1'))-t2.^2.*t22.*(t3.*(t15.*mp('6.0')+t19).*mp('4.5e+1')-t22.*(t15-t18)))+mp('1.0'))-t23.^4.*(c.*(t15.*mp('2.0')+t19)-mp('1.0'))+c.*dtt.*muu.*t23.^2.*(c.*(t5+t10+t14).*(t5+t10+t11+y2).*-mp('3.0')+t2.*t20.*(t4+t9+t14).*(t4+t9+t11+y2)+mp('4.0')).*mp('6.0'));
