function fbraux = fbrGram33(x1,y1,x2,y2,dtt,c,muu)
%FBRGRAM33
%    FBRAUX = FBRGRAM33(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    07-Nov-2019 04:20:22

t2 = -x2;
t3 = -y2;
t4 = t2+x1;
t5 = t3+y1;
t6 = t4.^2;
t7 = t5.^2;
fbraux = c.*mp('1.0')./(c.*(t6+t7)+mp('1.0')).^(mp('5.0')./mp('2.0')).*(c.*(t6-t7.*mp('2.0'))+mp('1.0'));
