function fbraux = fbrGram28(x1,y1,x2,y2,dtt,c,muu)
%FBRGRAM28
%    FBRAUX = FBRGRAM28(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    07-Nov-2019 04:25:32

t2 = c.^2;
t3 = x1.*mp('2.0');
t4 = x2.*mp('2.0');
t5 = -x2;
t7 = -y2;
t6 = -t4;
t8 = t5+x1;
t9 = t7+y1;
t10 = t8.^2;
t11 = t9.^2;
t12 = t11.*mp('1.1e+1');
t13 = t10+t11;
fbraux = muu.*t2.*mp('1.0')./(c.*t13+mp('1.0')).^(mp('1.3e+1')./mp('2.0')).*(c.*(t10.*-mp('1.9e+1')+t12+dtt.*muu.*mp('1.2e+2'))-t2.*(t13.*(t10.*mp('4.6e+1')-t11.*mp('9.0'))+dtt.*muu.*(t10.*mp('2.8e+1')+t13).*mp('6.0e+1'))+t2.^2.*t13.^2.*(t13.*(t3+t6+t9).*(t3+t6-y1+y2)-dtt.*muu.*(t10.*mp('6.0')-t11).*mp('1.5e+1'))-c.^3.*t13.*(t10.*t11.*mp('1.8e+1')+t10.^2.*mp('1.9e+1')-t11.^2-dtt.*muu.*(t10.*mp('1.01e+2')-t12).*mp('1.5e+1'))+mp('4.0')).*mp('3.0');
