function fbraux = fbrGram41(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRGRAM41
%    FBRAUX = FBRGRAM41(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Nov-2019 13:09:49

t2 = c.^2;
t3 = c.^3;
t4 = x1.*2.0;
t5 = x2.*2.0;
t6 = y1.*2.0;
t7 = y2.*2.0;
t8 = -x2;
t10 = -y1;
t11 = -y2;
t12 = dtt.*muu.*6.0e+1;
t9 = -t5;
t13 = t8+x1;
t14 = t11+y1;
t15 = t13.^2;
t17 = t14.^2;
t32 = t4+t9+t14;
t33 = t4+t9+t10+y2;
t16 = t15.^2;
t18 = t17.^2;
t19 = t15.*2.0;
t20 = t15.*3.0;
t22 = t17.*2.0;
t23 = t17.*5.0;
t25 = t15.*9.0;
t26 = t15.*1.1e+1;
t27 = t15.*3.3e+1;
t30 = t17.*2.3e+1;
t34 = t15+t17;
t35 = t15.*t17.*4.0;
t21 = t16.*7.0;
t24 = t18.*3.0;
t28 = -t23;
t31 = -t30;
t36 = t19+t22;
t39 = t12+t17+t26;
t40 = dtt.*muu.*(t23-t25).*-5.0;
t42 = dtt.*muu.*(t23-t25).*5.0;
t29 = -t24;
t37 = t25+t28;
t38 = t27+t31;
t41 = c.*t39;
t44 = t32.*t33.*t36;
t43 = dtt.*muu.*t38.*5.0;
t45 = t21+t29+t35+t42;
t46 = t43+t44;
t48 = t3.*t34.*t45;
t47 = t2.*t46.*2.0;
t49 = t41+t47+t48+2.0;
fbraux = muu.*t2.*1.0./(c.*t34+1.0).^(1.1e+1./2.0).*(NX2.^2.*t14.*t49-NY2.^2.*t14.*t49+NX2.*NY2.*t13.*(t2.*(t34.*(t17.*7.0-t20)-dtt.*muu.*(t15.*5.0-t17.*5.1e+1).*5.0)-c.*(t20-t22+dtt.*muu.*3.0e+1)+t3.*t34.*(dtt.*muu.*(t15-t17.*6.0).*5.0+t34.*(t6-t7+t13).*(t6-t7-x1+x2))-1.0).*4.0).*3.0;
