function fbraux = fbrAnzatz33(x1,y1,x2,y2,dtt,c,muu)
%FBRANZATZ33
%    FBRAUX = FBRANZATZ33(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Nov-2019 04:26:03

fbraux = 0.0;
