function fbraux = fbrAnzatz34(x1,y1,x2,y2,dtt,c,muu)
%FBRANZATZ34
%    FBRAUX = FBRANZATZ34(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Nov-2019 04:26:04

fbraux = 0.0;
