function fbraux = fbrGram17(x1,y1,x2,y2,dtt,c,muu)
%FBRGRAM17
%    FBRAUX = FBRGRAM17(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Nov-2019 04:24:03

t2 = c.^2;
t3 = y1.*2.0;
t4 = y2.*2.0;
t5 = -x2;
t6 = -y2;
t7 = t5+x1;
t8 = t6+y1;
t9 = t7.^2;
t10 = t8.^2;
t11 = t9.*1.1e+1;
t12 = t10.*1.9e+1;
t14 = t9+t10;
t13 = -t12;
fbraux = muu.*t2.*1.0./(c.*t14+1.0).^(1.3e+1./2.0).*(c.*(t11+t13+dtt.*muu.*1.2e+2)+t2.*(t14.*(t9.*9.0-t10.*4.6e+1)-dtt.*muu.*(t10.*2.8e+1+t14).*6.0e+1)+t2.^2.*t14.^2.*(dtt.*muu.*(t9-t10.*6.0).*1.5e+1+t14.*(t3-t4+t7).*(t3-t4-x1+x2))+c.^3.*t14.*(t14.*(t9+t13)+dtt.*muu.*(t10.*1.01e+2-t11).*1.5e+1)+4.0).*3.0;
