function fbraux = fbrGram28(x1,y1,x2,y2,dtt,c,muu)
%FBRGRAM28
%    FBRAUX = FBRGRAM28(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Nov-2019 04:25:32

t2 = c.^2;
t3 = x1.*2.0;
t4 = x2.*2.0;
t5 = -x2;
t7 = -y2;
t6 = -t4;
t8 = t5+x1;
t9 = t7+y1;
t10 = t8.^2;
t11 = t9.^2;
t12 = t11.*1.1e+1;
t13 = t10+t11;
fbraux = muu.*t2.*1.0./(c.*t13+1.0).^(1.3e+1./2.0).*(c.*(t10.*-1.9e+1+t12+dtt.*muu.*1.2e+2)-t2.*(t13.*(t10.*4.6e+1-t11.*9.0)+dtt.*muu.*(t10.*2.8e+1+t13).*6.0e+1)+t2.^2.*t13.^2.*(t13.*(t3+t6+t9).*(t3+t6-y1+y2)-dtt.*muu.*(t10.*6.0-t11).*1.5e+1)-c.^3.*t13.*(t10.*t11.*1.8e+1+t10.^2.*1.9e+1-t11.^2-dtt.*muu.*(t10.*1.01e+2-t12).*1.5e+1)+4.0).*3.0;
