function fbraux = fbrGram26(x1,y1,x2,y2,dtt,c,muu)
%FBRGRAM26
%    FBRAUX = FBRGRAM26(X1,Y1,X2,Y2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    07-Nov-2019 04:20:43

t2 = -x2;
t3 = -y2;
t4 = t2+x1;
t5 = t3+y1;
t6 = t4.^2;
t7 = t5.^2;
fbraux = c.*dtt.*1.0./(c.*(t6+t7)+1.0).^(5.0./2.0).*(c.*(t6-t7.*2.0)+1.0);
