function fbraux = fbrAnzatz32(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRANZATZ32
%    FBRAUX = FBRANZATZ32(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    05-Nov-2019 00:33:00

t2 = y1-y2;
fbraux = c.*dtt.*t2.*1.0./(c.*((x1-x2).^2+t2.^2)+1.0).^(3.0./2.0);
