function fbraux = fbrAnzatz23(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRANZATZ23
%    FBRAUX = FBRANZATZ23(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    05-Nov-2019 00:32:57

t2 = c.^2;
t3 = x1.*2.0;
t4 = x2.*2.0;
t5 = -x2;
t7 = -y2;
t6 = -t4;
t8 = t5+x1;
t9 = t7+y1;
t10 = t3+t6;
t11 = t8.^2;
t12 = t9.^2;
t13 = t11+t12;
t14 = c.*t13;
t15 = t14+1.0;
t16 = 1.0./t15.^(5.0./2.0);
fbraux = NY2.*(c.*1.0./t15.^(3.0./2.0)-t2.*t10.^2.*t16.*(3.0./4.0))+NX2.*t2.*t10.*t16.*(y1.*2.0-y2.*2.0).*(3.0./4.0);
