function fbraux = fbrAnzatz13(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRANZATZ13
%    FBRAUX = FBRANZATZ13(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    05-Nov-2019 00:32:53

t2 = c.^2;
t3 = y1.*2.0;
t4 = y2.*2.0;
t5 = -x2;
t6 = -y2;
t7 = -t4;
t8 = t5+x1;
t9 = t6+y1;
t10 = t8.^2;
t11 = t3+t7;
t12 = t9.^2;
t13 = t10+t12;
t14 = c.*t13;
t15 = t14+1.0;
t16 = 1.0./t15.^(5.0./2.0);
fbraux = NX2.*(c.*1.0./t15.^(3.0./2.0)-t2.*t11.^2.*t16.*(3.0./4.0))+NY2.*t2.*t11.*t16.*(x1.*2.0-x2.*2.0).*(3.0./4.0);
