function fbraux = fbrAnzatz31(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRANZATZ31
%    FBRAUX = FBRANZATZ31(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    05-Nov-2019 00:32:59

t2 = x1-x2;
fbraux = c.*dtt.*t2.*1.0./(c.*((y1-y2).^2+t2.^2)+1.0).^(3.0./2.0);
