function fbraux = fbrGram33(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRGRAM33
%    FBRAUX = FBRGRAM33(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    05-Nov-2019 00:32:18

t2 = c.^2;
t3 = x1.*2.0;
t4 = x2.*2.0;
t5 = y1.*2.0;
t6 = y2.*2.0;
t7 = -x2;
t9 = -y2;
t8 = -t4;
t10 = -t6;
t11 = t7+x1;
t12 = t9+y1;
t13 = t3+t8;
t14 = t11.^2;
t15 = t5+t10;
t16 = t12.^2;
t17 = t14+t16;
t18 = c.*t17;
t19 = t18+1.0;
t20 = 1.0./t19.^(3.0./2.0);
t21 = 1.0./t19.^(5.0./2.0);
t22 = c.*t20;
fbraux = NX1.*(NX2.*(t22-t2.*t15.^2.*t21.*(3.0./4.0))+NY2.*t2.*t13.*t15.*t21.*(3.0./4.0))+NY1.*(NY2.*(t22-t2.*t13.^2.*t21.*(3.0./4.0))+NX2.*t2.*t13.*t15.*t21.*(3.0./4.0));
