function fbraux = fbrGram34(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRGRAM34
%    FBRAUX = FBRGRAM34(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    05-Nov-2019 00:32:47

t2 = NX1.^2;
t3 = NY1.^2;
t4 = c.^2;
t5 = c.^3;
t6 = x1.*2.0;
t7 = x2.*2.0;
t8 = y1.*2.0;
t9 = y2.*2.0;
t10 = -x2;
t12 = -y2;
t11 = -t7;
t13 = -t9;
t14 = t10+x1;
t15 = t12+y1;
t16 = t6+t11;
t17 = t14.^2;
t18 = t8+t13;
t19 = t15.^2;
t20 = t16.^2;
t21 = t16.^3;
t22 = t18.^2;
t23 = t18.^3;
t24 = t17+t19;
t25 = c.*t24;
t26 = t25+1.0;
t27 = 1.0./t26.^(5.0./2.0);
t28 = 1.0./t26.^(7.0./2.0);
fbraux = NX2.*muu.*t2.*t4.*t18.*t27.*-3.0+NX2.*muu.*t3.*t4.*t18.*t27.*3.0+NX2.*muu.*t2.*t5.*t23.*t28.*(1.5e+1./8.0)-NX2.*muu.*t3.*t5.*t23.*t28.*(1.5e+1./8.0)-NY2.*muu.*t2.*t4.*t16.*t27.*3.0+NY2.*muu.*t3.*t4.*t16.*t27.*3.0+NY2.*muu.*t2.*t5.*t21.*t28.*(1.5e+1./8.0)-NY2.*muu.*t3.*t5.*t21.*t28.*(1.5e+1./8.0)+NX1.*NX2.*NY1.*muu.*t4.*t16.*t27.*6.0-NX1.*NY1.*NY2.*muu.*t4.*t18.*t27.*6.0-NX2.*muu.*t2.*t5.*t18.*t20.*t28.*(1.5e+1./8.0)+NX2.*muu.*t3.*t5.*t18.*t20.*t28.*(1.5e+1./8.0)-NY2.*muu.*t2.*t5.*t16.*t22.*t28.*(1.5e+1./8.0)+NY2.*muu.*t3.*t5.*t16.*t22.*t28.*(1.5e+1./8.0)-NX1.*NX2.*NY1.*muu.*t5.*t16.*t22.*t28.*(1.5e+1./2.0)+NX1.*NY1.*NY2.*muu.*t5.*t18.*t20.*t28.*(1.5e+1./2.0);
