function fbraux = fbrGram15(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRGRAM15
%    FBRAUX = FBRGRAM15(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    05-Nov-2019 00:32:51

t2 = -x2;
t3 = -y2;
t4 = t2+x1;
t5 = t3+y1;
t6 = t4.^2;
t7 = t5.^2;
t8 = t6+t7;
t9 = c.*t8;
t10 = t9+1.0;
fbraux = c.*dtt.*1.0./t10.^(3.0./2.0)-c.^2.*dtt.*1.0./t10.^(5.0./2.0).*(x1.*2.0-x2.*2.0).^2.*(3.0./4.0);
