function fbraux = fbrAnzatz13(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRANZATZ13
%    FBRAUX = FBRANZATZ13(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    07-Nov-2019 13:46:18

t2 = -x2;
t3 = -y2;
t4 = t2+x1;
t5 = t3+y1;
t6 = t4.^2;
t7 = t5.^2;
fbraux = c.*mp('1.0')./(c.*(t6+t7)+mp('1.0')).^(mp('5.0')./mp('2.0')).*(NX2+NX2.*c.*(t6-t7.*mp('2.0'))+NY2.*c.*t4.*t5.*mp('3.0'));
