function fbraux = fbrGram42(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRGRAM42
%    FBRAUX = FBRGRAM42(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    07-Nov-2019 13:37:59

t2 = c.^2;
t3 = c.^3;
t4 = x1.*mp('2.0');
t5 = x2.*mp('2.0');
t6 = y1.*mp('2.0');
t7 = y2.*mp('2.0');
t8 = -x2;
t11 = -y2;
t13 = dtt.*muu.*mp('6.0e+1');
t9 = -t5;
t10 = -t6;
t12 = -t7;
t14 = t8+x1;
t15 = t11+y1;
t16 = t14.^2;
t17 = t15.^2;
t30 = t7+t10+t14;
t31 = t6+t12+t14;
t18 = t16.*mp('2.0');
t19 = t16.*mp('3.0');
t20 = t16.*mp('5.0');
t21 = t17.*mp('2.0');
t22 = t17.*mp('7.0');
t23 = t16.*mp('2.3e+1');
t25 = t17.*mp('9.0');
t26 = t17.*mp('1.1e+1');
t27 = t17.*mp('3.3e+1');
t32 = t16+t17;
t24 = -t22;
t28 = -t25;
t29 = -t27;
t33 = t18+t21;
t37 = t13+t16+t26;
t34 = t19+t24;
t35 = t20+t28;
t36 = t23+t29;
t39 = c.*t37;
t44 = -t31.*t33.*(t6+t12-x1+x2);
t38 = dtt.*muu.*t35.*mp('5.0');
t41 = dtt.*muu.*t36.*mp('5.0');
t42 = -t39;
t43 = t32.*t34;
t40 = -t38;
t46 = t41+t44;
t48 = -t3.*t32.*(t38-t43);
t45 = t40+t43;
t47 = t2.*t46.*mp('2.0');
t49 = t42+t47+t48-mp('2.0');
fbraux = muu.*t2.*mp('1.0')./(c.*t32+mp('1.0')).^(mp('1.1e+1')./mp('2.0')).*(-NX2.^2.*t14.*(t39-t47+t3.*t32.*(t38-t43)+mp('2.0'))+NY2.^2.*t14.*(t39-t47+t3.*t32.*(t38-t43)+mp('2.0'))+NX2.*NY2.*t15.*(t2.*(t16.*t17.*mp('4.0')+t16.^2.*mp('7.0')-t17.^2.*mp('3.0')+dtt.*muu.*(t16.*mp('5.1e+1')-t17.*mp('5.0')).*mp('5.0'))-c.*(t17.*mp('3.0')-t18+dtt.*muu.*mp('3.0e+1'))+t3.*t32.*(t32.*(t4+t9+t15).*(t4+t9-y1+y2)-dtt.*muu.*(t16.*mp('6.0')-t17).*mp('5.0'))-mp('1.0')).*mp('4.0')).*-mp('3.0');
