function fbraux = fbrGram32(x1,y1,x2,y2,NX1,NY1,NX2,NY2,dtt,c,muu)
%FBRGRAM32
%    FBRAUX = FBRGRAM32(X1,Y1,X2,Y2,NX1,NY1,NX2,NY2,DTT,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    07-Nov-2019 13:36:14

t2 = x1.*mp('2.0');
t3 = x1.*mp('3.0');
t4 = x2.*mp('2.0');
t5 = x2.*mp('3.0');
t6 = -x2;
t9 = -y1;
t10 = -y2;
t7 = -t4;
t8 = -t5;
t11 = t6+x1;
t12 = t10+y1;
t13 = t11.^2;
t14 = t12.^2;
t15 = t13+t14;
t16 = c.*t15;
t17 = t16+mp('1.0');
t18 = t17.^2;
fbraux = (c.*mp('1.0')./t17.^(mp('9.0')./mp('2.0')).*(NY2.*t18.*(c.*t13.*-mp('8.0')+c.*t14.*mp('4.0')+mp('4.0')).*mp('4.0')+c.*dtt.*muu.*(NY2.*(c.*(t3+t8+t12).*(t3+t8+t9+y2).*-mp('3.0')+c.*t16.*(t2+t7+t12).*(t2+t7+t9+y2)+mp('4.0')).*mp('1.6e+1')-NX2.*c.*t11.*t12.*(t16-mp('6.0')).*mp('8.0e+1')).*mp('3.0')+NX2.*c.*t11.*t12.*t18.*mp('4.8e+1')))./mp('1.6e+1');
