function fbraux = fbrAnzatz32(x1,y1,x2,y2,c,muu)
%FBRANZATZ32
%    FBRAUX = FBRANZATZ32(X1,Y1,X2,Y2,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    29-Nov-2019 03:14:40

t2 = -y2;
t3 = t2+y1;
fbraux = c.*t3.*mp('1.0')./(c.*((x1-x2).^2+t3.^2)+mp('1.0')).^(mp('3.0')./mp('2.0'));
