function fbraux = fbrAnzatz33(x1,y1,x2,y2,c,muu)
%FBRANZATZ33
%    FBRAUX = FBRANZATZ33(X1,Y1,X2,Y2,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    29-Nov-2019 03:14:40

fbraux = mp('0.0');
