function fbraux = fbrGram14(x1,y1,x2,y2,c,muu)
%FBRGRAM14
%    FBRAUX = FBRGRAM14(X1,Y1,X2,Y2,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version mp('8.3').
%    29-Nov-2019 03:14:20

t2 = -x2;
t3 = -y2;
t4 = t2+x1;
t5 = t3+y1;
t6 = t4.^2;
t7 = t5.^2;
t8 = t6+t7;
t9 = c.*t8;
fbraux = c.^3.*muu.*t4.*t5.*mp('1.0')./(t9+mp('1.0')).^(mp('9.0')./mp('2.0')).*(t9-mp('6.0')).*-mp('1.5e+1');
