function fbraux = fbrAnzatz22(x1,y1,x2,y2,c,muu)
%FBRANZATZ22
%    FBRAUX = FBRANZATZ22(X1,Y1,X2,Y2,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    29-Nov-2019 03:14:37

t2 = c.^2;
t3 = x1.*2.0;
t4 = x1.*3.0;
t5 = x2.*2.0;
t6 = x2.*3.0;
t7 = -x2;
t10 = -y1;
t11 = -y2;
t8 = -t5;
t9 = -t6;
t12 = t7+x1;
t13 = t11+y1;
t14 = t12.^2;
t15 = t13.^2;
t16 = t14+t15;
fbraux = muu.*t2.*1.0./(c.*t16+1.0).^(9.0./2.0).*(c.*(t4+t9+t13).*(t4+t9+t10+y2).*-3.0+t2.*t16.*(t3+t8+t13).*(t3+t8+t10+y2)+4.0).*3.0;
