function fbraux = fbrGram36(x1,y1,x2,y2,c,muu)
%FBRGRAM36
%    FBRAUX = FBRGRAM36(X1,Y1,X2,Y2,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    29-Nov-2019 03:14:29

fbraux = 0.0;
