function fbraux = fbrGram46(x1,y1,x2,y2,c,muu)
%FBRGRAM46
%    FBRAUX = FBRGRAM46(X1,Y1,X2,Y2,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    29-Nov-2019 03:14:30

fbraux = 0.0;
