function fbraux = fbrGram45(x1,y1,x2,y2,c,muu)
%FBRGRAM45
%    FBRAUX = FBRGRAM45(X1,Y1,X2,Y2,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    29-Nov-2019 03:14:27

fbraux = 0.0;
