function fbraux = fbrGram31(x1,y1,x2,y2,c,muu)
%FBRGRAM31
%    FBRAUX = FBRGRAM31(X1,Y1,X2,Y2,C,MUU)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    29-Nov-2019 03:13:41

t2 = c.^2;
t3 = y1.*2.0;
t4 = y1.*3.0;
t5 = y2.*2.0;
t6 = y2.*3.0;
t7 = -x2;
t8 = -y2;
t9 = t7+x1;
t10 = t8+y1;
t11 = t9.^2;
t12 = t10.^2;
t13 = t11+t12;
fbraux = muu.*t2.*1.0./(c.*t13+1.0).^(9.0./2.0).*(c.*(t4-t6+t9).*(t4-t6-x1+x2).*-3.0+t2.*t13.*(t3-t5+t9).*(t3-t5-x1+x2)+4.0).*3.0;
